-- The events the home page listed before the events admin existed. Added
-- once, by `npm run db:schema`, when it creates the events table.

INSERT IGNORE INTO `ihern_events` (`seed_key`, `tag`, `title`, `description`, `speakers`, `starts_at`, `venue`, `mode`, `join_url`, `join_label`, `links`, `status`, `published_at`, `created_by`)
VALUES ('2026-09-21-sigs-webinar', 'IHERN SIGs Webinar', 'Inaugural IHERN Special Interest Groups (SIGs) Webinar', 'The inaugural IHERN Special Interest Groups (SIGs) Webinar will provide an opportunity to introduce the IHERN SIGs, discuss their objectives and proposed activities, and explore how members can become active participants in the activities of their SIGs.\n\nPlease fill in the Google Form to help us gauge your interest in the SIGs. Your responses will help us better understand the scope of the SIGs and enable us to develop meaningful activities for them.', '', '2026-09-21 10:30:00', 'Zoom', 'online', 'https://iiitd-ac-in.zoom.us/j/94327035439?pwd=xsH9qyEAaw06NawgiGPxvaCKpmhBLg.1', 'Join via Zoom', '[{"label": "SIGs interest form", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdPZszVfFi6JCnBbqNcnDhxQ9_MiSO1vuMUsMkj5AkWjvPnjA/viewform"}]', 'published', '2026-09-21 10:30:00', 'ihern@iiitd.ac.in');

INSERT IGNORE INTO `ihern_events` (`seed_key`, `tag`, `title`, `description`, `speakers`, `starts_at`, `venue`, `mode`, `join_url`, `join_label`, `links`, `status`, `published_at`, `created_by`)
VALUES ('2026-05-29-webinar', 'IHERN Webinar', 'Introducing the Emerging ''Components Toward an Indigenous Inclusive College Readiness Framework'' for Tribal Youth in India- Plus, Steps Forward', 'A session of the IHERN Higher Education Research Webinar Series, featuring a talk on Introducing the Emerging ''Components Toward an Indigenous Inclusive College Readiness Framework'' for Tribal Youth in India- Plus, Steps Forward. The talk will unpack the nuances of what it means to be ''college ready'' among the tribal youth of Odisha and Jharkhand, and how the knowledge gained can help them build a bridge program between the tribal communities and colleges.', 'Matthew A. Witenstein, Associate Professor of Educational Leadership and Policy, University of New Mexico\nAnthony J. Chipre, EdD Student, University of New Mexico', '2026-05-29 10:30:00', 'Zoom', 'online', '', '', '[{"label": "View webinar poster", "url": "/IHERN Webinar 29 May 2026.pdf"}]', 'published', '2026-05-29 10:30:00', 'ihern@iiitd.ac.in');

INSERT IGNORE INTO `ihern_events` (`seed_key`, `tag`, `title`, `description`, `speakers`, `starts_at`, `venue`, `mode`, `join_url`, `join_label`, `links`, `status`, `published_at`, `created_by`)
VALUES ('2026-04-23-webinar', 'IHERN Webinar', 'Integrating Research into Undergraduate Teacher Education', 'A session of the IHERN Higher Education Research Webinar Series, featuring a talk on Integrating Research into Undergraduate Teacher Education. The talk will delve into the nature of integrating research into higher education with special reference to initial teacher education, and an empirical study of a project(s) in the B.El.Ed teacher education degree programme of University of Delhi.', 'Dr. Gunjan Sharma, Associate Professor, School of Education Studies, Dr. B.R. Ambedkar University Delhi\nProf. Jyoti Raina, Professor of Education, Gargi College, University of Delhi', '2026-04-23 15:00:00', 'Zoom', 'online', '', '', '[{"label": "View webinar poster", "url": "/23rd Webinar Final IHERN.pdf"}]', 'published', '2026-04-23 15:00:00', 'ihern@iiitd.ac.in');
